baseURL: https://raccontimediterranei.abarc.it # todo: change site url.
title: Tra le terre, il mar
defaultContentLanguage: "it"
theme: eternity
googleAnalytics: "" # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: logo.png
  subtitle: Tra le terre, il mar - Mostra d'arte della collezione ABARC al Castello Ruffo di Scilla
  copyright: All rights reserved.
  author: Accademia di Belle Arti di Reggio Calabria
  dontShowSource: false
  portfolio:
    columns:
      desktop:
        archive: 5
        default: 3
      mobile:
        default: 2
        archive: 4
  socials:
    # todo: change these links.
    - icon: "far fa-envelope fa-lg"
      url: "mailto:info@abarc.it"
      landing: true
    - icon: "fab fa-facebook fa-lg"
      url: "https://www.facebook.com/accademiabelleartirc/"
      landing: true
    - icon: "fab fa-instagram fa-lg"
      url: "https://www.instagram.com/accademiabelleartirc/"
      landing: true
    - icon: "fab fa-youtube fa-lg"
      url: "https://www.youtube.com/channel/UCxqaMJYfzAX5-Xr4_bQ5uqg/featured"
      landing: true
  homepage: "/work"
  specialPages:
    - work
    - archive
  bypassWelcomePage: false
  disableWelcomePageBackground: false
  plausible: "" # todo: set your plausible id.
  disableRadius: true
  moveIt: false
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: archive
      url: /tags/archive/
      weight: 4
    - name: about
      url: /about/
      weight: 5
